# Generated by Django 5.0 on 2023-12-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='location',
        ),
    ]
